PROJECT_STATUS_OPEN = 'open'
PROJECT_STATUS_CLOSED = 'closed'

MAX_LENGTH_NAME = 200
MAX_LENGTH_USER_NAME = 124
MAX_LENGTH_USER_SURNAME = 124
MAX_LENGTH_PHONE = 12
MAX_LENGTH_STATUS = 6
MAX_LENGTH_ABOUT = 256

PAGINATE_BY = 12
